[package]
name = "dinoclone"
version = "0.1.0"
authors = ["Bulagro <christumer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.99"
noise   = "0.6"
rand    = "0.7"
shellexpand = "2.1"
